ChoiceA/Models/SelectViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChoiceA.Models
{
    public class SelectViewModel
    {
        public Student Student { get; set; }

        public List<CheckedModel> SelectedDiscipline { get; set; }

        public SelectViewModel()
        {

        }

        public SelectViewModel(Student student, List<CheckedModel> checkedModels)
        {
            Student = student;
            SelectedDiscipline = checkedModels;


        }


    }
}

ChoiceA/Controllers/DisciplinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChoiceA.Data;
using ChoiceA.Models;
using Microsoft.AspNetCore.Authorization;
using static ChoiceA.ActionResults.ForAdminFilter;

namespace ChoiceA.Controllers
{
    [ForAdmin]
    public class DisciplinesController : Controller
    {
        private readonly ChoiceContext _context;

        public DisciplinesController(ChoiceContext context)
        {
            _context = context;
        }

        // GET: Disciplines
        public async Task<IActionResult> Index()
        {
            return View(await _context.Disciplines.ToListAsync());
        }

        // GET: Disciplines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discipline = await _context.Disciplines
                .FirstOrDefaultAsync(m => m.Id == id);
            if (discipline == null)
            {
                return NotFound();
            }

            return View(discipline);
        }

        // GET: Disciplines/Create
        public IActionResult Create()
        {
            ViewData["TeacherName"] = new SelectList(_context.Teachers, "Id", "Name");
            return View();
        }

        // POST: Disciplines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Annotation,TeacherId")] Discipline discipline)
        {
            if (ModelState.IsValid)
            {
                _context.Add(discipline);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TeacherName"] = new SelectList(_context.Teachers, "Name", "Name", _context.Teachers.Where(x => x.Id == discipline.TeacherId).Select(x => x.Name));
            return View(discipline);
        }

        // GET: Disciplines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discipline = await _context.Disciplines.FindAsync(id);
            if (discipline == null)
            {
                return NotFound();
            }
            ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "Name", discipline.TeacherId);
            return View(discipline);
        }

        // POST: Disciplines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Annotation,TeacherId")] Discipline discipline)
        {
            if (id != discipline.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(discipline);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DisciplineExists(discipline.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                ViewData["TeacherId"] = new SelectList(_context.Teachers, "Id", "Id", discipline.TeacherId);
                return RedirectToAction(nameof(Index));
            }
            return View(discipline);
        }

        // GET: Disciplines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var discipline = await _context.Disciplines
                .FirstOrDefaultAsync(m => m.Id == id);
            if (discipline == null)
            {
                return NotFound();
            }

            return View(discipline);
        }

        // POST: Disciplines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var discipline = await _context.Disciplines.FindAsync(id);
            _context.Disciplines.Remove(discipline);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DisciplineExists(int id)
        {
            return _context.Disciplines.Any(e => e.Id == id);
        }
    }
}

ChoiceA/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChoiceA.Data;
using ChoiceA.Models;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using ChoiceA.Service;

namespace ChoiceA.Controllers
{
    [Authorize(Policy = "NotStudent")]
    public class StudentsController : Controller
    {
        private readonly ChoiceContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IGroupService _groupService;
        public StudentsController(ChoiceContext context,UserManager<ApplicationUser> userManager,IGroupService groupService)
        {
            _groupService = groupService;
            _userManager = userManager;
            _context = context;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var choiceContext = _context.Students.Include(s => s.ApplicationUser);
            return View(await choiceContext.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .Include(s => s.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            //ViewBag.Groups = new SelectList(_groupService.GetGroupList());
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Group")] Student student)
        {
            if (ModelState.IsValid)
            {
                // register new user
                var user = new ApplicationUser { UserName = student.Name, Email = $"{student.Name}@gmail.com",EmailConfirmed=true };
                var result = await _userManager.CreateAsync(user, "123456");

                if (result.Succeeded)
                {
                    // add new student
                    _context.Add(student);
                    await _context.SaveChangesAsync();

                  
                   await _userManager.AddClaimAsync(user, new Claim("studentId", student.Id.ToString()));
               
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Name", result.Errors.First().Description);
                }
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

        
            var student = await _context.Students.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            ViewData["Name"] = new SelectList(_context.ApplicationUsers, "Id", "Id", student.Name);
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Group")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Name"] = new SelectList(_context.ApplicationUsers, "Id", "Id", student.Name);
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Students
                .Include(s => s.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Students.FindAsync(id);
            _context.Students.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Students.Any(e => e.Id == id);
        }
    }
}

ChoiceA/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ChoiceA.Data;
using ChoiceA.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using static ChoiceA.ActionResults.ForAdminFilter;

namespace ChoiceA.Controllers
{
    [ForAdmin]
    public class TeachersController : Controller
    {
        private readonly ChoiceContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public TeachersController(ChoiceContext context,UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
            _context = context;
        }

        // GET: Teachers
        public async Task<IActionResult> Index()
        {
            var choiceContext = _context.Teachers.Include(t => t.ApplicationUser);
            return View(await choiceContext.ToListAsync());
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .Include(t => t.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // GET: Teachers/Create
        public IActionResult Create()
        {
            ViewData["Name"] = new SelectList(_context.ApplicationUsers, "Id", "Id");
            return View();
        }

        // POST: Teachers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,Name")] Teacher teacher)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(teacher);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["Name"] = new SelectList(_context.ApplicationUsers, "Id", "Id", teacher.Name);
        //    return View(teacher);
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Group")] Teacher teacher)
        {
            if (ModelState.IsValid)
            {
                // register new user
                var user = new ApplicationUser { UserName = teacher.Name, Email = $"{teacher.Name}@gmail.com", EmailConfirmed = true };
                var result = await _userManager.CreateAsync(user, "123456");

                if (result.Succeeded)
                {
                    // add new student
                    _context.Add(teacher);
                    await _context.SaveChangesAsync();


                    await _userManager.AddClaimAsync(user, new Claim("teacherId", teacher.Id.ToString()));

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                }
            }
            return View(teacher);
        }
        // GET: Teachers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers.FindAsync(id);
            if (teacher == null)
            {
                return NotFound();
            }
            ViewData["Name"] = new SelectList(_context.ApplicationUsers, "Id", "Id", teacher.Name);
            return View(teacher);
        }

        // POST: Teachers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Teacher teacher)
        {
            if (id != teacher.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(teacher);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeacherExists(teacher.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Name"] = new SelectList(_context.ApplicationUsers, "Id", "Id", teacher.Name);
            return View(teacher);
        }

        // GET: Teachers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var teacher = await _context.Teachers
                .Include(t => t.ApplicationUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (teacher == null)
            {
                return NotFound();
            }

            return View(teacher);
        }

        // POST: Teachers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var teacher = await _context.Teachers.FindAsync(id);
            _context.Teachers.Remove(teacher);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeacherExists(int id)
        {
            return _context.Teachers.Any(e => e.Id == id);
        }
    }
}

ChoiceA/Views/Home/ChatIndex.cshtml
@page
@model ChoiceA.Models.IndexModel
@{

}
@if (Model.Messages != null)
{
@foreach (var mes in Model.Messages)
{
    <div>
        <div style="font-size:larger">@mes.Text</div>
        <div style="font-size: smaller">@mes.Sign --- @mes.When</div>
    </div>
}}
<hr />
<div>
    <form method="post">
        <label asp-for="Text"></label>
        <input asp-for="Text" value="" />
        <input type="submit" value="Send" />
        <span asp-validation-for="Text"></span>
    </form>
</div>

ChoiceA/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">

    <a href="@Url.Action("Index", "Students")">Students</a><br />
    <a href="@Url.Action("Index", "Disciplines")">Disciplines</a><br />
    <a href="@Url.Action("Index", "Teachers")">Teachers</a>
</div>

ChoiceA/Views/Home/IndexModel.cshtml
@{
    ViewData["Title"] = "IndexModel";
}

<h1>IndexModel</h1>

ChoiceA/Views/Home/Select.cshtml
@model SelectViewModel
@{
    ViewData["Title"] = "Select";
}

<h1>Select</h1>

    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="@Model.Student.Id" class="form-control" />
    <input type="hidden" asp-for="@Model.Student.Name" class="form-control" />
    <input type="hidden" asp-for="@Model.Student.Group" class="form-control" />
    <div id="selectList">

        @for (int i = 0; i < Model.SelectedDiscipline.Count; i++)
        {


            <div >
                <input type="hidden" name="ckeckbox" asp-for="@Model.SelectedDiscipline[i].Discipline.Id" class="form-control" />
                <input type="hidden"  name="ckeckbox" asp-for="@Model.SelectedDiscipline[i].Discipline.Title" class="form-control" />

                @Html.DisplayFor(m => m.SelectedDiscipline[i].Discipline.Title,"nameCheck")
                <input type="checkbox" name="@Model.SelectedDiscipline[i].Discipline.Title" value=@Model.SelectedDiscipline[i].IsChecked checked=@Model.SelectedDiscipline[i].IsChecked/>
                @*@Html.EditorFor(m => m.SelectedDiscipline[i].IsChecked, "checkEdit")*@
            </div>
        }
    </div>

    <input type="button" id="elem" value="Изменить" onclick="send()" />

    <script type="text/javascript">
           
 function send() {
     const url = '/Home/SelectAjax';

         //let formData = new FormData();
         //let data = {
         //    IsChecked: true,
         //    Title: 'awfawf'
         //};
         //let xsrf_token = document.getElementsByName("__RequestVerificationToken")[0].value;
         //let formData = new FormData();

         //formData.append("str", data);
         //formData.append("data",DiscList);
         try {
             let DiscList = [];
        
             let a = document.querySelectorAll("input[type='checkbox']");
             a.forEach((item, i) => {
                 let elem = { IsChecked: item.checked, Title: item.name }
                 DiscList.push(elem)
             })
       
       
        $.ajax(url, {
            method: 'post',
            contentType: 'application/json',
            data: JSON.stringify(DiscList),
            traditional: true,
          
            success: function (data) {
                $("#selectList").replaceWith(data);
            }
        });
            //const response = await fetch(url, {
            //     //contentType: 'application/json',
            //    method: 'POST',
            //    data: JSON.stringify(data),
            //    traditional: true,
            //    credentials: 'include',
            //    headers: { "XSRF-TOKEN": xsrf_token, "Accept": "application/json", "Content-Type": "application/json" }, 
            //});
            //if (response.status === 200) {
            //    //const json = await response.json();
            //    //add_message(text, json.userName);
            //}
            //else {
            //    const text = await response.text();
            //    alert(text);
            //}
        } catch (error) {
            console.error('Ошибка:', error);
         }
     }

    </script>
    

ChoiceA/Views/Home/SelectList.cshtml
@model List<CheckedModel>
    <div id="selectList">
        @for (int i = 0; i < Model.Count; i++)
        {


            <div>
                <input type="hidden" asp-for="@Model[i].Discipline.Id" class="form-control" />
                <input type="hidden" asp-for="@Model[i].Discipline.Title" class="form-control" />

                @Html.DisplayFor(m => m[i].Discipline.Title, "nameCheck")
                <input type="checkbox" name="@Model[i].Discipline.Title" value=@Model[i].IsChecked checked=@Model[i].IsChecked />
            </div>
        }
    </div>